services:
  bot:
    image: ghcr.io/laptopcoder/ru-ege-telegram-bot:latest
    container_name: ru-ege-useful-info
    volumes:
      - /etc/localtime:/etc/localtime
      - db:/data/db
    environment:
      - PATH_TO_DB=/data/db/db.sqlite3
      - PATH_TO_INITIAL_SQL_QUERIES=/app/src/sql/init.sql
      - PATH_TO_GET_INFO_SQL_QUERIES=/app/src/sql/get_info.sql
    env_file:
      - .env
    restart: always
